name: PR Factory

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0/10 * * * *"

jobs:
  create-pr:
    # needs: merge-pr
    runs-on: [ubuntu-latest]
    steps:
      - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: choose secret
        id: choose-secret
        run: |
          case $(( RANDOM % 3 )) in
          0)
            echo "secret_name=Paul_PAT" >> $GITHUB_OUTPUT
            echo "Impersonating Paul"
            ;;
          1)
            echo "secret_name=PAUL_PAT" >> $GITHUB_OUTPUT
            echo "Impersonating Paul"
            ;;
          2)
            echo "secret_name=Paul_PAT" >> $GITHUB_OUTPUT
            echo "Impersonating Paul"
            ;;            
          esac

      - name: trunk install
        uses: trunk-io/trunk-action/install@v1
        with:
          tools: gh jq

      - name: download mq
        run: |
          gh release download --pattern='*.gz' --output mq.gz --clobber
          tar -xf mq.gz
        env:
          GH_TOKEN: ${{ secrets[steps.choose-secret.outputs.secret_name] }}

      - name: run mq
        id: edits
        run: ./mq
        env:
          GH_TOKEN: ${{ secrets[steps.choose-secret.outputs.secret_name] }}

      - name: run mq
        id: clean
        run: ./mq housekeeping
        env:
          GH_TOKEN: ${{ secrets[steps.choose-secret.outputs.secret_name] }}
